; toggle showing hidden files/directories with dired (M-o)
(require 'dired-x)
(setq-default dired-omit-files-p -1)  ; uncomment to change default behavior to hide files
(setq dired-omit-files
      (concat dired-omit-files "\\|^\\..+$"))

; nice buffer switching
(global-set-key (kbd "C-x C-b") 'ibuffer)

(setq ibuffer-show-empty-filter-groups nil)
(setq ibuffer-saved-filter-groups
      '(("default"
	 ("version control" (or (mode . svn-status-mode)
				(mode . svn-log-edit-mode)
				(name . "^\\*svn-")
				(name . "^\\*vc\\*$")
				(name . "^\\*Annotate")
				(name . "^\\*git-")
				(name . "^\\*vc-")))
	 ("emacs" (or (name . "^\\*scratch\\*$")
		      (name . "^\\*Messages\\*$")
		      (name . "^TAGS\\(<[0-9]+>\\)?$")
		      (name . "^\\*Help\\*$")
		      (name . "^\\*info\\*$")
		      (name . "^\\*Occur\\*$")
		      (name . "^\\*grep\\*$")
		      (name . "^\\*Compile-Log\\*$")
		      (name . "^\\*Backtrace\\*$")
		      (name . "^\\*Process List\\*$")
		      (name . "^\\*gud\\*$")
		      (name . "^\\*Man")
		      (name . "^\\*WoMan")
		      (name . "^\\*Kill Ring\\*$")
		      (name . "^\\*Completions\\*$")
		      (name . "^\\*tramp")
		      (name . "^\\*shell\\*$")
		      (name . "^\\*compilation\\*$")))
	 ("emacs source" (or (mode . emacs-lisp-mode)
			     (filename . "/Applications/Emacs.app")
			     (filename . "/bin/emacs")))
	 ("agenda" (or (name . "^\\*Calendar\\*$")
		       (name . "^diary$")
		       (name . "^\\*Agenda")
		       (name . "^\\*org-")
		       (name . "^\\*Org")
		       (mode . org-mode)
		       (mode . muse-mode)))
	 ("latex" (or (mode . latex-mode)
		      (mode . LaTeX-mode)
		      (mode . bibtex-mode)
		      (mode . reftex-mode)))
	 ("c/c++" (or (mode . c++-mode)
		      (mode . c-mode)))
	 ("xml"   (or (mode . nxml-mode)))
	 ("python"(or (mode . python-mode)))
	 ("dired" (or (mode . dired-mode))))))


(add-hook 'ibuffer-mode-hook
	  (lambda ()
	    (ibuffer-switch-to-saved-filter-groups "default")))
