; functions for inserting comments in txt (to keep it all uniform)
(defun insert-comment-note()
  (interactive)
  (newline-and-indent)
  (insert "/* NOTE:")
  (newline-and-indent)
  (insert " *")
  (newline-and-indent)
  (insert " *")
  (newline-and-indent)
  (insert " *")
  (newline-and-indent)
  (insert " */")
  (newline-and-indent)
)

(defun insert-comment-section()
  (interactive)
  (newline-and-indent)
  (insert-and-inherit "///////////////////////////////////")
  (newline-and-indent)
  (insert-and-inherit "//")
  (newline-and-indent)
  (insert-and-inherit "///////////////////////////////////")
)
